
@host = https://testdbuv.herokuapp.com

GET {{host}}/basedatos/consultatotalpacientes

###
PUT {{host}}/basedatos/insertarpacientes
Content-Type: application/json

{
    
    "nombre":"name2",
    "apellido":"lastname2",
    "numid":"1235"
}

###
POST {{host}}/actualizadatos
Content-Type: application/json

{
    "id":"12345",
    "nombre":"names",
    "apellido":"lastname"
}

###
DELETE {{host}}/borrar
Content-Type: application/json

{
"id":"1234567"
}