
@host = https://testdbuv.herokuapp.com

GET {{host}}/basedatos/consultatotalpacientes

###
PUT {{host}}/basedatos/insertarpacientes
Content-Type: application/json

{
    
    "nombre":"name1",
    "apellido":"lastname1",
    "numid":"1234"
}

###
POST {{host}}/basedatos/actualizadototalpacientes
Content-Type: application/json

{
    "nombre":"names",
    "apellido":"last",
    "numid":"1234"
}

###
DELETE {{host}}/basedatos/borradototalpacientes
Content-Type: application/json

{
"numid":"1234"
}